baseurl: "https://example.com" # Controls base URL
languageCode: "en-US" # Controls html lang attribute
title: "Connectome" # Homepage title and page title suffix
paginate: 12 # Number of posts to show before paginating
theme: "connectome" # to use as default theme

enableRobotsTXT: true # Suggested, it generates a robots.txt
googleAnalytics: "" # Optional, add tracking Id for analytics
SectionPagesMenu: "main" # Enable menu system for lazy bloggers


menu:
  main:
    - name: About
      weight: 1
      identifier: about
      url: /about/
  topright:
    - name: Posts
      weight: 1
      identifier: posts
      url: /posts/
    - name:
      weight: 2
      identifier: tags
      url: /tags/
      pre: '<i class="fas fa-tags"></i>'
    - name:
      weight: 3
      identifier: graph
      url: /graph
      pre: '<i class="fas fa-project-diagram"></i>'

taxonomies:
    tag: "tags"
    link: "links"

params:
  theme_variant: "lumen" # possible value for the theme_variant `cerulean,cosmo,cyborg,darkly,flatly,journal,litera,lumen,lux,materia,minty,pulse,sandstone,simplex,slate,solar,spacelab,superhero,united,yeti`
  description: "Connectume is a hugo theme for online communities such as reading clubs."
  favicon: "/logos/logo-square.png" # Path to favicon
  logo: "/logos/logo-square.png" # logo of the website
  projects: # This is the menu item for the list of projects and the title of project list page
    section: projects # The section where we list all the projects
    indicator: "Notebooks"
  splash: "/img/splash/undraw_to_the_moon_v1mv.svg" # This is the splash image for the landing page. The image is shown in the top left of the page.
  powered_by: "love" # Optional, controls name display on footer
  hide_author: false # Optional, set true to hide author name on posts
  images: # Suggested, controls default OpenGraph images controls author name display on meta tag
  github: "kausalflow" # Optional, to display link to github account in menu bar
  twitter: "" # Optional, to display link to twitter account in menu bar
  author: "KausalFlow" # Default author name and the name to be shown in the footer
  editURL: "https://github.com/kausalflow/hugo-connectome-theme-demo/edit/master/content/"
  utterances: # comment system: utterances (https://utteranc.es/) parameters
    repo: "kausalflow/hugo-connectome-theme-demo"  # repo="[ENTER REPO HERE]", the comments will appear as issues in this repository on github.
    term: pathname               # issue-term="pathname"
    theme: github-light          # theme="github-light"


outputFormats:
  data:
    baseName: "data"
    isPlainText: true
    mediaType: "application/json"
    notAlternative: true

outputs:
  home:
    - "HTML"
    - "RSS"
    - "data"
